### ISSUE TITLE
Env vars DB_NEO4J_HOST and DB_ELASTIC_HOST have no effect

### ISSUE THREAD

**Issue by ChristophB** [Onto-Med/top-backend#187]
Looks like Neo4J and Elasticsearch related configuration was restructured in c33081064d4f7b94a571ff2fb8ad23ea6a98dbe8. Now they are completely gone from `application.yml` and the backend always tries to connect to `localhost` regardless of what the env vars are set to.

![image](https://github.com/Onto-Med/top-backend/assets/1651973/17ef47ea-cdda-4d2f-84ae-833960703c89)

**Comment by fmatthies** [comment]
This is intended: for all the document related stuff one needs a proper configured adapter
```
top:
  [...]
  documents:
    data-source-config-dir: ${DOCUMENT_DATA_SOURCE_CONFIG_DIR:config/data_sources/nlp}
    default_adapter: ${DOCUMENT_DEFAULT_ADAPTER:#{null}}
```
if no adapter is given connections default to services default
