### ISSUE TITLE
Could not load text adapter configs from dir 'config/data_sources/nlp'

### ISSUE THREAD

**Issue by KonradHoeffner** [Onto-Med/top-backend#200]
Executing `docker compose up` in `top-deployment` results in the following backend warning:

    backend-1   | 2024-02-14 10:47:15.940  WARN 1 --- [nio-8080-exec-4] c.s.t.b.s.nlp.DocumentQueryService       : Could not load text adapter configs from dir 'config/data_sources/nlp'

**Comment by fmatthies** [comment]
Is this locally on your machine? This is an example of a text adapter config source:
```
id: Lucene Data Source
adapter: care.smith.top.top_document_query.adapter.lucene.LuceneAdapter
connection:
  url: http://localhost
  port: 9201
index:
  - test_documents
field:
  - text
batchSize: 30
replaceFields: {'text': 'content'}
graphDB:
  connection:
    url: bolt://localhost
    port: 7687
conceptGraph:
  connection:
    url: http://localhost
    port: 5000
```

Supposing, you don't have the services running locally, you could forward the ports from `top-prod`.
- `elasticSearch` (the main connection) runs on 9008
- `graphDB` runs on 7687
- `conceptGraph` runs on 9007
